services:
  # SERVICIO DE LA APLICACIÓN SUITECRM (Web/PHP)
  suitecrm:
    # Indica a Docker que construya la imagen con el Dockerfile en la misma carpeta
    build: ./
    networks:
      - suitecrm_net
    volumes:
      # Montaje del código de la aplicación (CRÍTICO)
      # El código de SuiteCRM debe estar dentro de la carpeta ./www en el repositorio
      - ./www:/var/www/html
      
      # Volúmenes para persistencia de Logs (No causan conflicto)
      - ./logs/SuiteCRM:/var/www/html/SuiteCRM/logs
      - ./logs/SuiteCRM_Core/suitecrm.log:/var/www/html/SuiteCRM/public/legacy/suitecrm.log
      - ./logs/apache:/var/log/apache2/
      - ./logs/php:/var/log/php/
      
    env_file:
      # Archivo de variables de entorno para la configuración de la BD
      - environment/sample.env
      
    # Eliminamos 'command:' para usar el entrypoint por defecto y evitar el fallo de SSL
    # Eliminamos la sección 'ports:' para que EasyPanel se encargue de la exposición
    restart: on-failure
    labels:
      - me.titmus.authors="jon@titmus.me"

  # SERVICIO DE LA BASE DE DATOS MYSQL
  mysql_crm:
    image: mysql
    # Eliminamos la sección 'ports:'
    environment:
      # Credenciales usadas por SuiteCRM y phpMyAdmin para conectarse
      - MYSQL_ROOT_PASSWORD=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=suitecrm
      - MYSQL_DATABASE=suitecrm
    volumes:
      # Volumen para persistencia de los datos de la BD
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - suitecrm_net
    restart: on-failure
    
  # SERVICIO PHP MY ADMIN (Herramienta de Gestión de BD)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      # Conexión interna a la BD
      - mysql_crm
    # Eliminamos la sección 'ports:'
    environment:
      - PMA_HOST=mysql_crm
      - PMA_USER=suitecrm
      - PMA_PASSWORD=suitecrm
    networks:
      - suitecrm_net
    restart: no

networks:
    suitecrm_net:
        driver: bridge
